# Database.
[database]
[[database.default]]
    link = "mysql:root:root@tcp(localhost:3306)/vprix"
    charset = "utf8mb4" #数据库编码
    debug = true
    dryRun = false #空跑
    maxIdle = "10" #连接池最大闲置的连接数
    maxOpen = "10" #连接池最大打开的连接数
    maxLifetime = "30" #(单位秒)连接对象可重复使用的时间长度
# Database logger.
[database.logger]
    Path = "./data/log/vprix/sql"
    Level = "all"
    Stdout = true


[gfcli]
[[gfcli.gen.dao]]
    link = "mysql:root:root@tcp(127.0.0.1:3306)/vprix"
    overwriteDao = false
    modelFile = "vprix.go"
    descriptionTag = true
    path = "./models/vprix"

